### ISSUE TITLE
How to set the Min value?

### ISSUE THREAD

**Issue by Reegan01** [gregacucnik/EditableSeekBar#1]
Thanks for this wonderful plugin. I want to set the Min value How to I do this?

**Comment by gregacucnik** [comment]
I've added the minValue attribute in version 1.2. However, having custom range complicates things quite a bit. Hopefully, i covered all issues regarding negative min/max values and onChange callbacks.

Let me know if you find any strange behaviour.

**Comment by Reegan01** [comment]
Thanks for reply. Maybe when I expect version 1.2 static release?

On 16-Dec-2015 4:11 pm, Grega Čučnik notifications@github.com wrote:

I've added the minValue attribute in version 1.2. However, having custom range complicates things quite a bit. Hopefully, i covered all issues regarding negative min/max values and onChange callbacks.

Let me know if you find any strange behaviour.

---

**Comment by gregacucnik** [comment]
What do you mean by static release? Version 1.2 is already available on jCenter.

**Comment by Reegan01** [comment]
Oh.. sorry for misunderstood. I still used your :package: library version 1.2. I mentioned the Min Value is seekbar starting value, not value. Ex: seekbar start 20 to 100 so we can get the value in between 20 to 100. your plugin have setValue() and setMaxValue() not setMinValue().

**Comment by gregacucnik** [comment]
You can set range by setRange(min, max) or separately by setMinValue(min), setMaxValue(max). This is also possible to set in xml with attributes. Min and Max can also be negative values.
